services:
    etcd:
        image: bitnami/etcd:latest
        container_name: etcd
        environment:
            - ETCD_ENABLE_V2=true
            - ALLOW_NONE_AUTHENTICATION=yes
            - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
            - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
        volumes:
            - etcd_data:/bitnami/etcd
        ports:
            - "2379:2379"
        networks:
            - apisix

    apisix:
        image: apache/apisix:latest
        container_name: apisix
        depends_on:
            - etcd
        volumes:
            - ./apisix/conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
        ports:
        - "9180:9180/tcp"
        - "9080:9080/tcp"
        - "9091:9091/tcp"
        - "9443:9443/tcp"
        - "9092:9092/tcp"
        networks:
            - apisix

    dashboard:
        image: apache/apisix-dashboard:latest
        container_name: dashboard
        volumes:
            - ./apisix_dashboard/conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml:ro
        depends_on:
            - etcd
        ports:
            - "9000:9000/tcp"
        networks:
            - apisix

    demo1:
        image: apisixapidemo:latest
        container_name: demo1
        ports:
            - "8080:8080"
        environment:
            - SERVICE_NAME=One
        networks:
            - apisix

    demo2:
        image: apisixapidemo:latest
        container_name: demo2
        ports:
            - "8081:8080"
        environment:
            - SERVICE_NAME=Two
        networks:
            - apisix

networks:
    apisix:
        driver: bridge

volumes:
    etcd_data:
        driver: local